### ISSUE TITLE
The hamburger menu - home button does not redirect

### ISSUE THREAD

**Issue by Maycol-Espinoza-Ponce** [datagrove/marketplace#110]
**Describe the bug**

Within the hamburger menu, the "Home" option doesn't redirect anywhere. This happens regardless of whether you're logged in or not.

**To Reproduce**
**1. Go to login (it's not necessary)
2. Click on 'hamburger menu, Home option'**

<img width="1783" alt="Screenshot 2023-08-28 at 15 16 05" src="https://github.com/datagrove/marketplace/assets/122275107/5e2beae0-30be-4114-b329-76f3fa43587f">

**Expected behavior**
**Normally, I would expect that clicking on the "Home" option would redirect me to the homepage.**

**Screenshots**
<img width="1764" alt="Screenshot 2023-08-28 at 15 21 34" src="https://github.com/datagrove/marketplace/assets/122275107/30184eff-7494-403a-8de1-0e64bcc5fa61">

**Desktop (please complete the following information):**
- Environment (LocalHost or Hosted Website?)
    - If localhost can you replicate the bug on the Hosted Website
 - Browser [e.g. chrome, safari] **Chrome**
 - Browser Version [e.g. 22] **Version 116.0.5845.96 (Official Build) (arm64)**
 - UI Language **English**

**Additional context**
None

**Proposed Solution**
Any suggestions to resolve the issue.

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
Was able to replicate. Home <a> tag does not have an href. Resolved in commit e024e0c61ce7b49687310c8a25a1a2ffcb82c166
