### ISSUE TITLE
Button to go back within the navigation

### ISSUE THREAD

**Issue by Maycol-Espinoza-Ponce** [datagrove/marketplace#114]
**Is your feature request related to a problem? Please describe.**

When navigating within the website, for example: 

1. I log in as a provider.
2. I click on the hamburger menu.
3. I select the "My Provider Profile" option and click on it.
4. I can see my posts and click on one of them.
5. I want to go back to where I could see the other posts, but I'm not sure how. My first thought is: where is the back button?

**Describe the solution you'd like**

Having a back button for mobile navigation would be beneficial. While in desktop mode, we can use the browser's back arrow, but it would be more comprehensive to have a button for going back within the website itself.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by r-southworth** [comment]
@Maycol-Espinoza-Ponce Does the browser back button not work? Not sure tracking someone's path through the site makes sense when the browser already does that.

**Comment by Maycol-Espinoza-Ponce** [comment]
Yes you're right, I was thinking more about mobile, but mobile also has a
back button. I do not think it's necessary.
