### ISSUE TITLE
Major Muni filter not working

### ISSUE THREAD

**Issue by Maycol-Espinoza-Ponce** [datagrove/marketplace#116]
**Describe the bug**
When I log into my account, create some posts, and then navigate to the posts section, I use filters to easily find the posts I've recently made. However, the following situation occurs:

When I apply all three filters (Major Municipality, Minor Municipality, Governing District) with the corresponding locations for the recently created posts, these posts do not appear.

On the other hand, if I only apply one or two of the following filters: Minor Municipality or Governing District, then it works and the related searches appear.

In summary, the Major Municipality filter is currently not functioning.

**To Reproduce**
1. Login as Provider and as Client too.
3. Click Find Services.
4. Apply a filter or multiple filters.
 

**Expected behavior**
It's expected that all filters work individually or together, whether one, two, or all three filters are applied.

It was also tested in mobile device size and it didn't work either.

**Screenshots**

![screencapture-site-devurl-marketplace-4xm-pages-dev-services-2023-08-29-10_18_00](https://github.com/datagrove/marketplace/assets/122275107/d9e561fb-5c97-45bb-8ac2-dfef0bad433f)

![screencapture-site-devurl-marketplace-4xm-pages-dev-services-2023-08-29-10_15_29](https://github.com/datagrove/marketplace/assets/122275107/31381788-4a03-4239-80fd-f276b9b59bd8)

**Desktop (please complete the following information):**

- Environment (LocalHost or Hosted Website?) 
- https://marketplace-4xm.pages.dev/services 
- https://site-devurl.marketplace-4xm.pages.dev/services 

(NOTE: The localhost does not work for me, in fact it does not even show me the buttons to start a session.)

- OS: [e.g. iOS] Mac iOS
 - Browser [e.g. chrome, safari] Chrome
 - Browser Version [e.g. 22] Version 116.0.5845.96 (Official Build) (arm64)
 - UI Language English

**Additional context**
none

**Comment by r-southworth** [comment]
@Maycol-Espinoza-Ponce are you sure there are current posts that meet your filter criteria?

**Comment by Maycol-Espinoza-Ponce** [comment]
I made some updates to the report, things that I had not taken into account

**Comment by r-southworth** [comment]
Resolved.
