### ISSUE TITLE
Can't create post as client

### ISSUE THREAD

**Issue by Maycol-Espinoza-Ponce** [datagrove/marketplace#117]
**Describe the bug**
After creating an account as a provider and making posts as a provider, I clicked on the hamburger menu and selected the "Create Client Account" option, which worked well; I was able to successfully create the account. However, when I attempted to create a post as a client, the client option didn't seem to appear in the hamburger menu. Only the option for the provider was visible. As a result, I clicked on the only available option for creating a post, and indeed, the post was created, but it was attributed to a provider role, not a client role.

**To Reproduce**
1. Go login as a client
2. Click hamburguer menu.
3. Select the 'Create Post' option.

**Expected behavior**
I believe the expectation is that the client should be able to create a post where they can express their need for a certain type of service. However, I'm not entirely sure if this makes sense.

**Screenshots**

<img width="1753" alt="IssueCreatePostAsClient" src="https://github.com/datagrove/marketplace/assets/122275107/e640f326-6ad0-40de-a3f6-cead3efc97c4">

**Desktop (please complete the following information):**
- Environment (LocalHost or Hosted Website?)
- https://marketplace-4xm.pages.dev/services
- https://site-devurl.marketplace-4xm.pages.dev/services

(NOTE: The localhost does not work for me, in fact it does not even show me the buttons to start a session.)

- OS: [e.g. iOS] Mac iOS
 - Browser [e.g. chrome, safari] Chrome
 - Browser Version [e.g. 22] Version 116.0.5845.96 (Official Build) (arm64)
 - UI Language English

**Additional context**
none

**Proposed Solution**
I actually have no idea how to solve it.

**Comment by r-southworth** [comment]
Expected behavior. Clients aren't supposed to be able to post.
