### ISSUE TITLE
Sign Up - Last Name Tool Tips Icon Z-Index

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace#217]
**Describe the bug**
The text that appears when you hover over a tool tip icon sometimes renders off screen or at a lower z-index than it should

**To Reproduce**
1. Go to 'signup' page
2. View screen size medium or large
3. Hover over the First Name tool tip
4. The icon associated with the Last Name tool tip appears on top of the tool tip text that describes how to use the First Name field

**Expected behavior**
When the user overs over the First Name tool tip icon, text describing how the First Name input works should appear "over" the Last Name tool tips icon. The Last Name tool tips icon should no longer be visible.

**Screenshots**
<img width="669" alt="SignUpToolTips" src="https://github.com/datagrove/marketplace/assets/80067572/2c205f32-72f7-4f79-a771-e77ff1a15ab8">

**Proposed Solution**
Update the z-index of the Last Name tool tips icon

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
Resolved with PR https://github.com/datagrove/marketplace/pull/236
