### ISSUE TITLE
Add margin to the index banner.

### ISSUE THREAD

**Issue by RaqueAbarca** [datagrove/marketplace#223]
**Is your feature request related to a problem? Please describe:**
The banner seems not to be centered, as on the right side, there appears to be more margin or padding than on the left side.

**Describe the solution you'd like:**
Adding margin to the left would be a good solution, as it makes the page look a bit more compact and centered.

**Additional context**

![image](https://github.com/datagrove/marketplace/assets/149972748/03469cc5-d0b0-488c-a6ea-4b912f2760bc)

**Comment by r-southworth** [comment]
We appreciate the feedback.
