### ISSUE TITLE
The email confirmation link isn't working days later.

### ISSUE THREAD

**Issue by RaqueAbarca** [datagrove/marketplace#224]
**Describe the bug:**
I am having trouble confirming my email because I 'signed up' for the account on Friday but did not confirm the email immediately. A couple of days later (Sunday), the link to confirm my email no longer works. However, when I try to log in, it still asks me to confirm the email."

**To Reproduce:**

1. Register a new email.
2. Wait a few days.
3. Try to confirm the email from the link that arrived in your inbox (the link will no longer work, and the email cannot be confirmed).
4. Attempt to register or log in again with that email (it won't be possible because it hasn't been confirmed).

**Expected behavior:**

One would expect the link to work for confirming the email or when the page indicates the need for confirmation, there should be an option to resend the email confirmation.

**Screenshots**
![image](https://github.com/datagrove/marketplace/assets/149972748/de796492-eb68-4e23-96ab-1e94106425e3)

**Desktop (please complete the following information):**
- Environment (LocalHost or Hosted Website?): Website (Google Chrome)
- OS: iOS
 - Browser : Google Chrome
 - Browser Version: Version 119.0.6045.105

**Proposed Solution**
Enable an option/link to resend the email confirmation.

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
Updated in commit https://github.com/datagrove/marketplace/commit/845036a87dba78723ef07ed3e3565dd91c93c824
