### ISSUE TITLE
Change texts/descriptions

### ISSUE THREAD

**Issue by RaqueAbarca** [datagrove/marketplace#226]
**Is your feature request related to a problem? Please describe:**
There are texts, titles, or descriptions in Spanish that are not very clear or could be improved for a more familiar and straightforward vocabulary.

**Describe the solution you'd like**

Change “publicar contenido” for “descripción del servicio”
![image](https://github.com/datagrove/marketplace/assets/149972748/265a3bb2-f648-4175-95c9-2bc357c66d6f)

Change “Borrar Municipio Importante/Menor/etc...” for “Borrar Cantón/Distrito/etc...”
![image](https://github.com/datagrove/marketplace/assets/149972748/5b844950-eaa5-446d-bee6-438feaa014b9)

**Comment by r-southworth** [comment]
Addressed in multiple PRs including https://github.com/datagrove/marketplace/pull/230
