### ISSUE TITLE
LocationFilter.tsx

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace#64]
Some Governing Districts are appearing twice

**Comment by r-southworth** [comment]
Not sure this is incorrect unless it is happening in the same Province/Canton? It is like cities in the US there a lots of states with cities named the same thing.

**Comment by r-southworth** [comment]
Spot checked a bunch of these and there really are 5 districts in CR named San José for example they are all in different Minor Municipalities (Canton) so this is expected behavior.

**Comment by r-southworth** [comment]
Closing issue for now if we find duplicates in a single minor municipality please reopen.
