### ISSUE TITLE
Password error font

### ISSUE THREAD

**Issue by tomasdozier** [datagrove/marketplace#74]
Change font color to a RED or some color that gives a more clearer alert that there is an error.

**Comment by r-southworth** [comment]
Updated password requirements to be easier to read. Specifically what error were you concerned about?

**Comment by r-southworth** [comment]
@tomasdozier Do you feel this has been sufficiently addressed? https://marketplace-4xm.pages.dev/signup

If not please provide further details.

**Comment by r-southworth** [comment]
@tomasdozier Does this address the issue?

<img width="169" alt="Screenshot 2023-08-27 at 8 39 47 PM" src="https://github.com/datagrove/marketplace/assets/105446541/9ee67913-f082-45f6-ae70-9779f12cca36">
<img width="175" alt="Screenshot 2023-08-27 at 8 39 56 PM" src="https://github.com/datagrove/marketplace/assets/105446541/522ae59c-dbe5-4b6e-9989-bd7aed83a81e">

**Comment by tomasdozier** [comment]
yes!!!
