### ISSUE TITLE
difference of page between translations

### ISSUE THREAD

**Issue by tomasdozier** [datagrove/marketplace#76]
![Screenshot 2023-08-16 130553](https://github.com/datagrove/marketplace/assets/110420988/287fcbf1-cba7-4ebc-ad77-5bafe018d46c)
![Screenshot 2023-08-16 130631](https://github.com/datagrove/marketplace/assets/110420988/f105df9f-1ac0-436a-b14c-3120f22c28f6)
When switching between translations on the home page the footer looks different.  I believe the Spanish file has many of these written out. Just making a note of it as I am assuming we are going with the simpler layout.

**Comment by r-southworth** [comment]
Yes this is expected behavior - when the footer if finalized they will match.
